spring:
  datasource:
      username: root
      password: 123456
      schema: schema/schema.sql
      data: schema/data.sql
#  persistenceType: jdbc

mysql:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/spitter?useUnicode=true&characterEncoding=UTF-8

embed:
  url: jdbc:h2:mem:test_db
  driver: org.h2.Driver

hibernate:
#  do not use any properties file in the future
  properties: hibernate/hibernate.properties
#  show_sql: true
#  format_sql: false
#  cache:
#    use_second_level_cache: false
  JpaVendorAdapter:
    h2:
      dialect: org.hibernate.dialect.H2Dialect
    mysql:
      dialect: org.hibernate.dialect.MySQL5Dialect
  entity:
    package: com.wangy.webmvc.entity
